# Generated by Django 4.2.4 on 2023-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20, null=True, verbose_name='title')),
                ('content', models.CharField(default='', max_length=20, null=True, verbose_name='content')),
            ],
        ),
    ]
