# Generated by Django 4.2 on 2023-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=10, null=True, verbose_name='email')),
                ('name', models.CharField(default='', max_length=10, null=True, verbose_name='name')),
                ('password', models.CharField(default='', max_length=10, verbose_name='password')),
            ],
        ),
    ]
